### PR TITLE
Optional no cover layout and enhancements proposal

### PR DESCRIPTION
**Pull request by dreyacosta**
This is a proposal that you are free to discuss.

Here are some of the changes:

## 1. Header and post header with flexbox.
Why? Less CSS to deal with positioning. The target of the blog are engineers so I think we don't have to worry about browsers support.

**Before**
01 before-header-postheader-flexbox

**After**
02 after-header-postheader-flexbox

## 2. Footer with flexbox. Header code reused.

**Before**
03 before-footer-with-flexbox

**After**
04 after-footer-with-flexbox

## 3. Consistency between headings and paragraphs spaces.

**Before**
05 before-consistent-spaces

**After**
06 after-consistent-spaces

## 4. More consistency between spaces and site width.

**Before**
07 before-more-consistent-spaces

**After**
08 after-more-consistent-spaces

## 5. Optional no cover post layout.

09 optional-no-cover-post-layout

Comments are welcome :wink:

### CODE REVIEW

**Comment by IvanGuardado** [comment]
Ameising! @dreyacosta FTW!

**Comment by Kikobeats** [comment]
In addition could be nice setup a good vertical rhythm: http://zellwk.com/blog/why-vertical-rhythms/

I applied this in my blog and the results was amazing

btw, :+1:

**Comment by javivelasco** [comment]
Rico rico

**Comment by IvanGuardado** [comment]
In addition to @Kikobeats, so do it! :D

**Comment by dreyacosta** [comment]
@Kikobeats it sounds great. We can open another PR with your proposal.

**Comment by franholmo** [comment]
:+1:

**Comment by aartiles** [comment]
Great work David!
Who is the owner of the blog? I mean, who should approve the PRs? Not me :walking: :smile:

**Comment by javivelasco** [comment]
:walking:

**Pull request merged**
